import 'dart:convert';
import 'package:share_plus/share_plus.dart';
import '../../data/models/analysis_result.dart';

class ExportUtils {
  static Future<void> shareAsJSON(AnalysisResult result) async {
    final jsonString = const JsonEncoder.withIndent(
      '  ',
    ).convert(result.toJson());

    await SharePlus.instance.share(ShareParams(text: jsonString,
      title: 'VCF Analysis Results - ${result.patientId}',));
  }

  static Future<void> shareAsText(AnalysisResult result) async {
    final text = _generateTextReport(result);
    await SharePlus.instance.share(ShareParams(text: text,
      title: 'VCF Analysis Report - ${result.patientId}',));
  }

  static String _generateTextReport(AnalysisResult result) {
    return '''
VCF STRATIFICATION REPORT
========================

Patient ID: ${result.patientId}
Analysis Date: ${result.analysisDate}
Overall Risk: ${result.overallRisk.displayName}

SUMMARY
-------
${result.riskInterpretation}

STATISTICS
----------
Total Variants: ${result.statistics.totalVariants}
High Risk: ${result.statistics.highRiskCount}
Moderate Risk: ${result.statistics.moderateRiskCount}
VUS: ${result.statistics.vusCount}
Low Risk: ${result.statistics.lowRiskCount}

RECOMMENDATIONS
---------------
${result.recommendations.map((r) => '• [${r.priority.name.toUpperCase()}] ${r.title}').join('\n')}

---
Generated by VCF Stratifier
    ''';
  }
}
